# Generated by Django 3.2.13 on 2022-05-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_gig_time_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gig',
            options={'ordering': ['date']},
        ),
    ]
