# Generated by Django 3.2.13 on 2022-05-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_gig_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True, verbose_name='Venue Website'),
        ),
    ]
