# Generated by Django 3.2.13 on 2022-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_venue_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='agency_tax',
            field=models.IntegerField(blank=True, default=5, verbose_name='Agency Tax in %'),
        ),
    ]
